package com.lunatech.qnr.model.entities
import com.lunatech.qnr.model.Identifiable

///
///
/// Base class for every entities generated by a DataSource delegate
protected abstract class BaseEntity(a_id: Int) extends Identifiable {
  /// Every entity must have an uniq id
  protected val id: Int = a_id
  def ident = id
}
